// The site's middleware Edge Script: maps hosts to `/deploys/{id}/` origin paths and rewrites root-absolute asset URLs in path-preview HTML (see AGENTS.md and the SOURCE comments below). BunnySDK hook and HTMLRewriter names are the platform contract.
export const routerSource = `// bunny sites router, generated by the bunny CLI. Do not edit:
// \`bunny sites upgrade-router\` overwrites this script.
import * as BunnySDK from "@bunny.net/edgescript-sdk";

const PREVIEW_HOST = /^dpl-([a-z0-9]{4,40})\\.preview\\./i;
const PREVIEW_HEADER = "x-bunny-preview";
const RETRY_HEADER = "x-bunny-index-retry";
const DEPLOY_PATH = /^\\/deploys\\/([a-z0-9]{4,40})\\//i;

const NO_DEPLOYS_PAGE = \`<!doctype html>
<html><head><meta charset="utf-8"><title>No deploys yet</title></head>
<body style="font-family: system-ui, sans-serif; text-align: center; padding-top: 4rem">
<h1>Nothing here yet 🐇</h1>
<p>This site has no published deploys. Run <code>bunny sites deploy</code> to publish one.</p>
</body></html>\`;

// A slashless URL's directory-index retry target (/blog -> /blog/); null when the path already ends with a slash.
function indexRetryUrl(rawUrl) {
  const u = new URL(rawUrl);
  if (u.pathname.endsWith("/")) return null;
  u.pathname += "/";
  return u.toString();
}

// Prefix root-absolute, un-prefixed paths with the deploy dir; leave everything else alone.
function withDeploy(id, value) {
  if (!value || value[0] !== "/" || value[1] === "/") return value;
  if (value.startsWith("/deploys/")) return value;
  return "/deploys/" + id + value;
}

function rewriteAttr(id, attr) {
  return {
    element(el) {
      const v = el.getAttribute(attr);
      if (v) el.setAttribute(attr, withDeploy(id, v));
    },
  };
}

function rewriteSrcset(id) {
  return {
    element(el) {
      const v = el.getAttribute("srcset");
      if (!v) return;
      const out = v
        .split(",")
        .map((part) => {
          const seg = part.trim().split(/\\s+/);
          seg[0] = withDeploy(id, seg[0]);
          return seg.join(" ");
        })
        .join(", ");
      el.setAttribute("srcset", out);
    },
  };
}

BunnySDK.net.http
  .servePullZone()
  .onOriginRequest(async (ctx) => {
    const url = new URL(ctx.request.url);
    // Storage serves no directory indexes: expand \`/dir/\` to \`/dir/index.html\` on every route, path previews included.
    if (url.pathname.endsWith("/")) url.pathname += "index.html";
    const path = url.pathname;

    // Internal site metadata (state, env) is never served.
    if (path === "/_bunny" || path.startsWith("/_bunny/")) {
      return new Response("Forbidden", { status: 403 });
    }

    // Both flags are router-internal: client-sent copies are stripped, or they'd poison cached HTML.
    const headers = new Headers(ctx.request.headers);
    headers.delete(PREVIEW_HEADER);
    headers.delete(RETRY_HEADER);

    // Exact objects win: a slashless GET/HEAD miss retries as its directory index in the response phase.
    if (ctx.request.method === "GET" || ctx.request.method === "HEAD") {
      const retry = indexRetryUrl(ctx.request.url);
      if (retry) headers.set(RETRY_HEADER, retry);
    }

    // Path preview: serve the deploy dir directly, flagging the request so the response phase rewrites its HTML.
    if (path === "/deploys" || path.startsWith("/deploys/")) {
      const match = DEPLOY_PATH.exec(path);
      if (match) headers.set(PREVIEW_HEADER, match[1].toLowerCase());
      return new Request(new Request(url.toString(), ctx.request), { headers });
    }

    const preview = PREVIEW_HOST.exec(url.hostname);
    const deploy = preview
      ? preview[1].toLowerCase()
      : process.env.CURRENT_DEPLOY || "";

    if (!deploy) {
      return new Response(NO_DEPLOYS_PAGE, {
        status: 404,
        headers: { "Content-Type": "text/html; charset=utf-8" },
      });
    }

    url.pathname = "/deploys/" + deploy + path;
    return new Request(new Request(url.toString(), ctx.request), { headers });
  })
  .onOriginResponse(async (ctx) => {
    let response = ctx.response;

    // A flagged 404 probes its directory index and redirects to the slash URL when it exists (/blog -> /blog/), so relative references resolve against the right base; the probe re-enters this router and, slash-terminated, can never retry further.
    const retry = ctx.request.headers.get(RETRY_HEADER);
    if (retry && response.status === 404) {
      const probe = await fetch(retry, { method: "HEAD" });
      if (probe.ok) {
        return new Response(null, { status: 301, headers: { Location: retry } });
      }
    }

    const previewId = ctx.request.headers.get(PREVIEW_HEADER);
    const isCustomPreview = PREVIEW_HOST.test(new URL(ctx.request.url).hostname);
    if (!previewId && !isCustomPreview) return;

    // Path previews serve under a subpath: rewrite root-absolute asset refs into the deploy.
    const contentType = response.headers.get("content-type") || "";
    if (previewId && contentType.includes("text/html")) {
      response = new HTMLRewriter()
        .on("a[href]", rewriteAttr(previewId, "href"))
        .on("link[href]", rewriteAttr(previewId, "href"))
        .on("script[src]", rewriteAttr(previewId, "src"))
        .on("img[src]", rewriteAttr(previewId, "src"))
        .on("img[srcset]", rewriteSrcset(previewId))
        .on("source[src]", rewriteAttr(previewId, "src"))
        .on("source[srcset]", rewriteSrcset(previewId))
        .transform(response);
    }

    // Previews must never be indexed.
    const headers = new Headers(response.headers);
    headers.set("X-Robots-Tag", "noindex");
    return new Response(response.body, {
      status: response.status,
      statusText: response.statusText,
      headers,
    });
  });
`;
