/**
 * The site router — a middleware Edge Script attached to the site's pull zone.
 *
 * It maps incoming hosts to deploy directories inside the storage-zone origin:
 *
 * - apex / `.b-cdn.net` host        → `/deploys/{CURRENT_DEPLOY}{path}`
 * - `dpl-{id}.preview.{domain}`     → `/deploys/{id}{path}` (with `X-Robots-Tag: noindex`)
 * - `/deploys/{id}/...` paths       → passed through (path-based previews)
 * - `/_bunny/*`                     → 403 (site state/env are never served)
 *
 * Promote/rollback is just updating the `CURRENT_DEPLOY` env var — the code
 * itself never changes between deploys. Bump {@link ROUTER_VERSION} whenever
 * the source changes; `sites show` warns and `sites upgrade-router` republishes.
 */
export const ROUTER_VERSION = 1;

// NOTE: validated by the Phase 0 spike against the live platform; the exact
// BunnySDK middleware hook names are the platform contract this encodes.
const SOURCE = `// bunny sites router v__ROUTER_VERSION__ — generated by the bunny CLI. Do not edit:
// \`bunny sites upgrade-router\` overwrites this script.
import * as BunnySDK from "@bunny.net/edgescript-sdk";

const PREVIEW_HOST = /^dpl-([a-z0-9]{4,40})\\.preview\\./i;

const NO_DEPLOYS_PAGE = \`<!doctype html>
<html><head><meta charset="utf-8"><title>No deploys yet</title></head>
<body style="font-family: system-ui, sans-serif; text-align: center; padding-top: 4rem">
<h1>Nothing here yet 🐇</h1>
<p>This site has no published deploys. Run <code>bunny sites deploy</code> to publish one.</p>
</body></html>\`;

BunnySDK.net.http
  .servePullZone()
  .onOriginRequest(async (ctx) => {
    const url = new URL(ctx.request.url);
    const path = url.pathname;

    // Internal site metadata (state, env) is never served.
    if (path === "/_bunny" || path.startsWith("/_bunny/")) {
      return new Response("Forbidden", { status: 403 });
    }

    // Path-based previews address a deploy directory directly.
    if (path === "/deploys" || path.startsWith("/deploys/")) {
      return;
    }

    const preview = PREVIEW_HOST.exec(url.hostname);
    const deploy = preview
      ? preview[1].toLowerCase()
      : process.env.CURRENT_DEPLOY || "";

    if (!deploy) {
      return new Response(NO_DEPLOYS_PAGE, {
        status: 404,
        headers: { "Content-Type": "text/html; charset=utf-8" },
      });
    }

    let target = path;
    if (target.endsWith("/")) target += "index.html";
    url.pathname = "/deploys/" + deploy + target;
    return new Request(url.toString(), ctx.request);
  })
  .onOriginResponse(async (ctx) => {
    // Previews must never be indexed.
    if (!PREVIEW_HOST.test(new URL(ctx.request.url).hostname)) return;
    const headers = new Headers(ctx.response.headers);
    headers.set("X-Robots-Tag", "noindex");
    return new Response(ctx.response.body, {
      status: ctx.response.status,
      statusText: ctx.response.statusText,
      headers,
    });
  });
`;

export function routerSource(): string {
  return SOURCE.replace("__ROUTER_VERSION__", String(ROUTER_VERSION));
}
