// The published router source's generation; recorded in site state so deploy republishes routers that predate the current source.
export const ROUTER_VERSION = 4;

// The site's middleware Edge Script: rewrites every request to the published deploy's directory. The edge hands the script an origin-facing URL (an internal `ip:9000` address), so the client hostname MUST come from the CDN-Host/Host headers. (See AGENTS.md and the SOURCE comments below; BunnySDK hook and header names are the platform contract.)
export const routerSource = `// bunny sites router v${ROUTER_VERSION}, generated by the bunny CLI. Do not edit:
// \`bunny sites upgrade-router\` overwrites this script.
import * as BunnySDK from "@bunny.net/edgescript-sdk";

const RETRY_HEADER = "x-bunny-index-retry";

// ctx.request.url carries the ORIGIN address at the edge, not the requested host; the platform passes the client hostname in CDN-Host (Host covers local harnesses).
function clientHostname(request) {
  const fromHeader =
    request.headers.get("cdn-host") ?? request.headers.get("host");
  return (fromHeader ?? new URL(request.url).hostname).toLowerCase();
}

const NO_DEPLOYS_PAGE = \`<!doctype html>
<html><head><meta charset="utf-8"><title>No deploys yet</title></head>
<body style="font-family: system-ui, sans-serif; text-align: center; padding-top: 4rem">
<h1>Nothing here yet 🐇</h1>
<p>This site has no published deploys. Run <code>bunny sites deploy</code> to publish one.</p>
</body></html>\`;

// A slashless URL's directory-index retry target (/blog -> /blog/) on the client host, so the probe re-enters the CDN (and this router) instead of hitting the storage origin's unrouted paths; null when the path already ends with a slash.
function indexRetryUrl(rawUrl, host) {
  const u = new URL(rawUrl);
  if (u.pathname.endsWith("/")) return null;
  return "https://" + host + u.pathname + "/" + u.search;
}

BunnySDK.net.http
  .servePullZone()
  .onOriginRequest(async (ctx) => {
    const url = new URL(ctx.request.url);
    const host = clientHostname(ctx.request);
    // Storage serves no directory indexes: expand \`/dir/\` to \`/dir/index.html\` on every route.
    if (url.pathname.endsWith("/")) url.pathname += "index.html";
    const path = url.pathname;

    // Internal site metadata (state, env) is never served.
    if (path === "/_bunny" || path.startsWith("/_bunny/")) {
      return new Response("Forbidden", { status: 403 });
    }

    // The flag is router-internal: client-sent copies are stripped, or they'd poison cached HTML.
    const headers = new Headers(ctx.request.headers);
    headers.delete(RETRY_HEADER);

    // Exact objects win: a slashless GET/HEAD miss retries as its directory index in the response phase.
    if (ctx.request.method === "GET" || ctx.request.method === "HEAD") {
      const retry = indexRetryUrl(ctx.request.url, host);
      if (retry) headers.set(RETRY_HEADER, retry);
    }

    const deploy = process.env.CURRENT_DEPLOY || "";

    if (!deploy) {
      return new Response(NO_DEPLOYS_PAGE, {
        status: 404,
        headers: { "Content-Type": "text/html; charset=utf-8" },
      });
    }

    url.pathname = "/deploys/" + deploy + path;
    return new Request(new Request(url.toString(), ctx.request), { headers });
  })
  .onOriginResponse(async (ctx) => {
    // A flagged 404 probes its directory index and redirects to the slash URL when it exists (/blog -> /blog/), so relative references resolve against the right base; the probe re-enters this router and, slash-terminated, can never retry further.
    const retry = ctx.request.headers.get(RETRY_HEADER);
    if (retry && ctx.response.status === 404) {
      const probe = await fetch(retry, { method: "HEAD" });
      if (probe.ok) {
        return new Response(null, { status: 301, headers: { Location: retry } });
      }
    }
  });
`;
